// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkqgwwomtzmnzevwjaeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrcWd3d29tdHptbnpldndqYWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMTM1ODcsImV4cCI6MjA2ODc4OTU4N30.bgv6B3rMmUicC5u8OGumC6rsIR_cMzswUcnjaxpcefA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});